import Link from "next/link";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
  <ClerkProvider>
    {children}
  </ClerkProvider>
  <Link
  href="/upload"
  className="fixed bottom-6 right-6 group z-50"
>
  <div
    className="
      w-14 h-14
      rounded-full
      bg-white
      text-black
      flex items-center justify-center
      text-3xl font-bold
      shadow-xl
      transition-all duration-300
      hover:w-36
      hover:rounded-2xl
      overflow-hidden
    "
  >
    <span className="mr-0 group-hover:mr-2 transition-all">
      +
    </span>

    <span
      className="
        max-w-0
        opacity-0
        group-hover:max-w-xs
        group-hover:opacity-100
        transition-all duration-300
        whitespace-nowrap
        text-base font-semibold
      "
    >
      Upload
    </span>
  </div>
</Link>
</body>
    </html>
  );
}
